version: '3.8'

services:
  ${{ SERVICE_NAME }}:
    container_name: ${{ SERVICE_NAME }}
    image: simonfong6/${{ SERVICE_NAME }}:0.0.1
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - ${{ SERVICE_PORT }}:${{ SERVICE_PORT }}
    # Debug section.
    command: /bin/bash
    working_dir: /workspace
    volumes:
      - .:/workspace

networks:
  default:
    name: ${{ SERVICE_NAME }}
