apiVersion: v1
kind: Service
metadata:
  name: ${{ SERVICE_NAME }}
  labels:
    app: ${{ SERVICE_NAME }}
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: ${{ EXTERNAL_PORT }}
      targetPort: ${{ SERVICE_PORT }}
  # Replace with the IP of your minikube node / master node
  externalIPs:
    - 192.168.64.2
    - 172.17.0.4
  selector:
    app: ${{ SERVICE_NAME }}
    tier: backend
